version: "3"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/main/:/db/main/

  cities-project:
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8080:8080"