create schema if not exists cities;

create table if not exists cities.city
(
    id bigint not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) not null,
    picture_url text not null
    );

create table if not exists cities.users
(
    user_id uuid not null primary key,
    email varchar(45) not null,
    username varchar(45) not null,
    password varchar(64) not null,
    enabled boolean DEFAULT NULL
);

create table if not exists cities.roles (
    role_id uuid not null primary key,
    name varchar(45) not null
);

create table if not exists cities.users_roles (
    user_id uuid not null,
    role_id uuid not null,
    CONSTRAINT role_fk FOREIGN KEY (role_id) REFERENCES cities.roles (role_id),
    CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES cities.users (user_id)
);
